version: "3.9"
services:
    go-app:
        build:
            dockerfile: Dockerfile
            context: .
        container_name: "go-app"
        ports:
            - 8080:8080
        environment:
            - psql_host=psql-db
            - psql_port=5432
            - psql_user=test-user
            - psql_passwd=test-password
            - psql_dbname=test-database
        restart: unless-stopped
        networks:
            - go-app

    psql-db:
        image: "postgres:13-alpine"
        container_name: "psql-db"
        environment:
            - POSTGRES_USER=test-user
            - POSTGRES_PASSWORD=test-password
            - POSTGRES_DB=test-database
        volumes:
            - psql-db:/var/lib/postgresql
        restart: unless-stopped
        networks:
            - go-app

volumes:
    psql-db:

networks:
    go-app:
        name: fishka-network
