on: [push]

name: check and deploy

jobs:
  build_container:
    name: Build and publish container
    runs-on: ubuntu-20.04
    if: github.ref == 'refs/heads/main'
    steps:
      - uses: actions/checkout@v2

      - name: Set up QEMU
        uses: docker/setup-qemu-action@v1

      - name: Set up Docker Buildx  
        uses: docker/setup-buildx-action@v1

      - name: Login to DockerHub
        uses: docker/login-action@v1
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}

      - name: Build and push build-example
        id: docker_build_example
        uses: docker/build-push-action@v2
        with:
          context: ./build-example/.
          push: true
          tags: adrixop95/build-example-cloud-native-workshop:latest,adrixop95/build-example-cloud-native-workshop:${{ github.sha }}

      - name: Build and push compose-example
        id: docker_compose_example
        uses: docker/build-push-action@v2
        with:
          context: ./compose-example/.
          push: true
          tags: adrixop95/compose-example-cloud-native-workshop:latest,adrixop95/compose-example-cloud-native-workshop:${{ github.sha }}

  scan_container:
    name: Scan latest container
    needs: [docker_build_example, docker_compose_example]
    runs-on: ubuntu-20.04
    if: github.ref == 'refs/heads/master'
    steps:
      - uses: azure/container-scan@v0
        with:
          image-name: registry.hub.docker.com/adrixop95/build-example-cloud-native-workshop:${{ github.sha }}
      - uses: azure/container-scan@v0
        with:
          image-name: registry.hub.docker.com/adrixop95/compose-example-cloud-native-workshop:${{ github.sha }}
